database: h2
server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    #    driverClassName: com.mysql.jdbc.Driver
    schema: "classpath*:db/${database}/schema.sql"
    data: "classpath*:db/${database}/data.sql"
    #    url: "jdbc:mysql://localhost:3306/planner"
    #    username: ${MYSQL_USER:planner}
    #    password: ${MYSQL_PASS:planner}
    initialization-mode: always
    url: "jdbc:h2:mem:plannerdb"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    show-sql: true
#    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect

  boot:
    admin:
      client:
        url: http://localhost:8080
      context-path: /admin

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: debug

