database: h2
server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
#    driverClassName: com.mysql.jdbc.Driver
    schema: "classpath*:db/${database}/schema.sql"
    data: "classpath*:db/${database}/data.sql"
#    url: "jdbc:mysql://localhost:3306/planner"
#    username: ${MYSQL_USER:planner}
#    password: ${MYSQL_PASS:planner}
    initialization-mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
#    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect